spring:
  application:
    name: spring-demo

  datasource:
    url: jdbc:postgresql://localhost:5432/ojt
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

logging:
  level:
    com.example: DEBUG
  file:
    name: logs/cardSystem.log
